### ISSUE TITLE
Hi Jakub

### ISSUE THREAD

**Issue by benjasl-stripe** [jkapuscik2/php-lambda#1]
This is great stuff, and i think youre article is very easy to follow too. I think it'd be good to have a link to this on the AWS resources list for Serverless PHP. If you'd to do so, please make a PR to:
https://github.com/aws-samples/php-examples-for-aws-lambda/blob/master/serverless-php-resources.md

**Comment by jkapuscik2** [comment]
Hi Ben, thank you for reaching out. I have added a PR https://github.com/aws-samples/php-examples-for-aws-lambda/pull/19
